# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# variables:
# - name: system.debug
#   value: true

trigger:
- main

pool:
  vmImage: ubuntu-latest

# steps:
# - script: echo this is main
# - task: AzureResourceManagerTemplateDeployment@3
#   inputs:
#     deploymentScope: 'Resource Group'
#     action: 'Create Or Update Resource Group'
#     templateLocation: 'Linked artifact'
#     deploymentMode: 'Incremental'
stages:
- stage: Stage1
  jobs:
  - job: Job1
    steps:
      - script: echo stage1
- stage: Stage2
##########################################  
  jobs:
  - deployment: VMDeploy   # name of the deployment job
    displayName: web  # friendly name to display in the UI
    environment:
      name: testRH02  # environment name
      resourceType: VirtualMachine
      tags: vm2
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              whoami
              cd /home/fanny0608/branchtest
              git pull
              git diff --name-status HEAD~1..HEAD
            





