# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: MyGitHubDemo
      endpoint: xiafanfan
      type: github
      name: xiafanfan/GitHubDemo
      ref: main

extends:
  template: test.yml@MyGitHubDemo
  parameters:
    name: Mini
    testFile: tests/miniSuite.js

# stages:
# - template: test.yml  # Template reference
#   parameters:
#     name: Mini
#     testFile: tests/miniSuite.js


# - template: test.yml  # Template reference
#   parameters:
#     name: Full
#     testFile: tests/fullSuite.js

# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
